# Generated by Django 4.2.3 on 2023-08-02 22:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='default-image.jpg', null=True, upload_to=''),
        ),
    ]
