# Generated by Django 4.2.3 on 2023-08-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_categoria_pelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Posts.categoria'),
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
