# Generated by Django 4.2.3 on 2023-08-05 23:46

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default=Posts.models.default_author, max_length=100),
        ),
    ]
